server:
  port: 80

spring:
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 100MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
    username: root
    password: 2020121t

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect

itemImgLocation: /Users/LeeYeEun/Documents/dev/tmax/shop/img

uploadPath: /Users/LeeYeEun/Documents/dev/tmax/shop/uploads

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
